apiVersion: v2
name: netapp-openshift-console-trident
description: "NetApp Trident Console Plugin for Red Hat OpenShift ecosystem provides a single pane integration with NetApp Intelligent Data Management solutions for containers and virtual machines"
type: application
version: 26.2.1
appVersion: "26.2.1"