apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "netapp-connector.name" . }}
    component: {{ .Values.ui.name }}
spec:
  selector:
    matchLabels:
      app: {{ include "netapp-connector.name" . }}
      component: {{ .Values.ui.name }}
  serviceName: {{ .Values.ui.name }}
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "netapp-connector.name" . }}
        component: {{ .Values.ui.name }}
    spec:
      containers:
        - name: {{ .Values.ui.name }}
          image: "{{ .Values.ui.image.repository }}:{{ default .Chart.AppVersion .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: {{ .Values.ui.service.port | quote }}
            - name: NEO_API
              value: http://{{ .Values.main.name }}:{{ .Values.main.service.port }}
      restartPolicy: Always