apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "netapp-connector.name" . }}
    component: {{ .Values.ui.name }}
spec:
  selector:
    app: {{ include "netapp-connector.name" . }}
    component: {{ .Values.ui.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.env.PORT }}
  type: {{ .Values.ui.service.type }}