{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "netapp-connector.name" . }}
    component: {{ .Values.postgresql.name }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username }}
  password: {{ .Values.postgresql.auth.password }}
  database: {{ .Values.postgresql.auth.database }}
{{- end }}